// murdock-react/src/Select.tsx
import { SelectComponent, SelectProps } from 'murdock-core';
import { useHeadlessComponent, } from './index.ts';
import './Select.css';

export const Select = <T,>({ searchFunction, itemToString, debounce, selectedItem, setSelectedItem, limit }: SelectProps<T>) => {
    const state = useHeadlessComponent(SelectComponent<T>, { searchFunction, debounce, itemToString, selectedItem, setSelectedItem, limit });
    return (
        <>
            <input className='mk-input' onClick={state.onInputClick} value={state.search} onFocus={() => state.setFocused(true)} onBlur={() => state.setFocused(true)} onInput={(e) => state.setSearch(e.currentTarget.value)} />
            {state.open &&
                <div className='mk-input-dropdown-wrapper'>
                    <div className='mk-input-dropdown' >
                        {state.searchResults?.map(item => <p style={{ cursor: 'pointer' }} onClick={() => item.setSelected(true)}>{state.itemToString(item.item)}</p>)}
                    </div>
                </div >
            }
        </>
    )
}

// murdock-vue/src/SelectComponent.tsx
import type { FunctionalComponent } from 'vue';
import { type SelectStateVue } from './main';

export function FunctionalComponent<T>(props: SelectStateVue<T>) {
    return (
        <div>
            <input
                class="mk-input"
                onClick={props.onInputClick}
                value={props.search}
                onFocus={() => props.setFocused(true)}
                onBlur={() => props.setFocused(true)}
                onInput={e => { props.setSearch((e.target as HTMLInputElement).value); }}
            />
            {props.open && (
                <div class="mk-input-dropdown-wrapper">
                    <div class="mk-input-dropdown">
                        {props.searchResults?.map(item => (
                            <p style={{ cursor: 'pointer' }} onClick={() => item.setSelected(true)}>
                                {props.itemToString(item.item)}
                            </p>
                        ))}
                    </div>
                </div>
            )}
        </div>
    );
}
