// murdock-angular/projects/murdock-angular/src/lib/select/select.component.ts
/* eslint-disable @angular-eslint/component-selector */
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { SelectProps, SelectState, SelectComponent as MKSelect } from '@murdock-ui/murdock-core';
import '@murdock-ui/murdock-core/select.css';
import { HeadlessAngularComponent, HeadlessClass } from '../base.component';
@Component({
	selector: 'select-component',
	template: `<div [id]="state.id" [class]="state.rootClassName" [style]="{ width: state.width }">
		<div class="mk-select-wrapper">
			<input
				#searchBox
				class="mk-select-input"
				[value]="state.search"
				[placeholder]="state.placeholder || ''"
				(blur)="state.setFocused(false)"
				(focus)="state.setFocused(true)"
				(input)="state.setSearch !== undefined && state.setSearch(searchBox.value)"
				(keydown)="state.handleKey($event)"
				(click)="state.onInputClick()"
			/>

			@if (state.fetching) {
				<div class="mk-select-progress-bar">
					<div class="mk-select-progress-bar-value"></div>
				</div>
			}
			@if (state.selectedItem === null) {
				<button (click)="state.onMenuButtonClick()" class="mk-select-menu-button"></button>
			} @else {
				<button (click)="state.onClearButtonClick()" class="mk-select-clear-button"></button>
			}
		</div>

		<div class="mk-select-dropdown-wrapper">
			<div
				[style]="{ opacity: state.searchResults?.length && state.open ? 1 : 0 }"
				#listRef
				[class]="{ 'mk-select-dropdown': true, hidden: !state.open }"
				(load)="state?.listRef(listRef)"
			>
				@for (item of state.searchResults; track itemToString(item.item)) {
					<div
						aria-hidden="true"
						[class]="{ 'mk-select-dropdown-item': true, 'focus-item': item.focused }"
						(click)="item.setSelected(true)"
					>
						{{ itemToString(item.item) }}
					</div>
				}
			</div>
			<!-- This is a bit of a hack to get the list's ref into the state manager, has to be a better way -->
			<div style="display:none">
				{{ state?.listRef(listRef) }}
			</div>
			<div style="display:none">
				{{ state?.inputRef(searchBox) }}
			</div>
		</div>
	</div>`,
	standalone: true
})
export class SelectComponent<T>
	extends HeadlessAngularComponent<SelectProps<T>, SelectState<T>>
	implements HeadlessClass<SelectProps<T>, SelectState<T>>
{
	@Input() searchFunction?: (search: string, abortController: AbortController) => Promise<T[]>;
	@Input() itemToString: (item: T) => string = (item: T) => item as unknown as string;
	@Input() sort?: (a: T, b: T) => number;
	@Input() disabled?: boolean | undefined;
	@Input() width?: number;
	@Input() items?: T[];
	@Input() search?: string;
	@Input() placeholder?: string;
	@Input() selectedItem?: T | null;
	@Input() debounce?: number;
	@Input() id?: string;
	@Input() overrideClassName?: string;
	@Input() limit?: number;
	@Output() selectedItemChange: EventEmitter<T> = new EventEmitter<T>();
	@Output() searchChange: EventEmitter<string> = new EventEmitter<string>();
	override component = MKSelect;
}

// murdock-vue/src/SelectComponent.vue
<script setup lang="ts" generic="T = unknown">
import { SelectComponent as MKSelect, type SelectProps } from '@murdock-ui/murdock-core';
import { onBeforeUpdate, onMounted, onUnmounted } from 'vue';
import { useHeadlessComponent } from './index';
const props = defineProps<SelectProps<T>>();
const emit = defineEmits(['update:search', 'update:selectedItem']);

const { state, renderCount } = useHeadlessComponent(
	MKSelect<T>,
	props,
	emit,
	onMounted,
	onUnmounted,
	onBeforeUpdate
);
</script>

<template>
	<div :id="state.id" :className="state.rootClassName" :style="{ width: state.width + 'px' }">
		<div class="mk-select-wrapper">
			<input
				:ref="state.inputRef"
				className="mk-select-input"
				:value="state.search"
				:placeholder="state.placeholder"
				@click="() => state.onInputClick()"
				@input="(e) => state.setSearch((e.currentTarget as HTMLInputElement)?.value)"
				@blur="() => state.setFocused(false)"
				@focus="() => state.setFocused(true)"
				:style="{ width: state.width + 'px' }"
				@keydown="(e) => state.handleKey(e)"
				:disabled="disabled"
			/>

			<div v-if="state.fetching" className="mk-select-progress-bar">
				<div className="mk-select-progress-bar-value"></div>
			</div>

			<button
				v-if="state.selectedItem === null"
				@click="state.onMenuButtonClick()"
				className="mk-select-menu-button"
				:disabled="disabled"
			/>

			<button
				v-if="state.selectedItem !== null"
				@click="state.onClearButtonClick()"
				className="mk-select-clear-button"
				:disabled="disabled"
			/>
		</div>
		<div style="display: none">{{ renderCount }}</div>
		<div className="mk-select-dropdown-wrapper">
			<div
				:style="{ opacity: state.searchResults?.length && state.open ? 1 : 0 }"
				:ref="state.listRef"
				:className="`mk-select-dropdown${!state.open ? ' hidden' : ''}`"
			>
				<div
					:className="`mk-select-dropdown-item` + (item.focused ? ' focus-item' : '')"
					v-bind:key="props.itemToString(item.item as T)"
					v-for="item in state.searchResults"
					@click="() => item.setSelected(true)"
				>
					{{ props.itemToString(item.item as T) }}
				</div>
			</div>
		</div>
	</div>
</template>

<style src="@murdock-ui/murdock-core/select.css" scoped></style>
