// vue-examples/src/App.vue
<script setup lang="ts">
import { onBeforeUpdate, onMounted, ref } from 'vue';
import { faker } from '@faker-js/faker';
import SelectComponent from '@murdock-ui/murdock-vue/select-component';
type Country = {
	name: {
		common: string;
	};
};

type Animal = {
	id: number;
	name: string;
};

const selectedItem = ref<Country | null>(null);
const wait = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
let latency = 300;
const searchFunction = async (
	value: string,
	abortController: AbortController
): Promise<Country[]> => {
	const results = await fetch('https://restcountries.com/v3.1/name/' + value, {
		signal: abortController.signal
	});
	await wait(latency);
	if (abortController.signal.aborted) {
		throw new Error('Aborted');
	}
	return await results.json();
};
const itemToString = (item: Country | null): string => {
	return item?.name.common ?? '';
};

const fakerFuncs = [
	faker.animal.bear,
	faker.animal.cat,
	faker.animal.dog,
	faker.animal.type,
	faker.animal.fish,
	faker.animal.lion,
	faker.animal.snake,
	faker.animal.cetacean,
	faker.animal.cow,
	faker.animal.horse,
	faker.animal.insect,
	faker.animal.rabbit
];

const animalToString = (animal: Animal | null): string => animal?.name ?? '';

function getStaticData(length: number): Animal[] {
	// Generate length animal names
	const animals: Set<string> = new Set();
	let loops = 0;
	while (animals.size < length && loops < 1000) {
		const name = fakerFuncs[Math.floor(Math.random() * fakerFuncs.length)]();

		animals.add(name[0].toUpperCase() + name.slice(1));
		loops++;
	}
	return Array.from(animals).map((name, index) => ({ id: index, name }));
}

function updateStyles() {
	document.body.style.setProperty('--mk-select-max-menu-height', popupHeight.value + 'px');
	document.body.style.setProperty('--mk-corner-radius', cornerRadius.value + 'px');
	document.body.style.setProperty('--mk-text-color', textColor.value);
	document.body.style.setProperty('--mk-primary-color', primaryColor.value);
	document.body.style.setProperty('--mk-background-color', backgroundColor.value);
	document.body.style.setProperty('--mk-padding', padding.value + 'px');
	document.body.style.setProperty('--mk-select-height', height.value + 'px');
	document.body.style.setProperty('--mk-select-width', width.value + 'px');
	document.body.style.setProperty('--mk-select-font', font.value);
	document.body.style.setProperty('--mk-animation-speed', animationSpeed.value + 'ms');
}
onBeforeUpdate(() => {
	updateStyles();
});

onMounted(() => {
	updateStyles();
});

const selectedAnimal = ref<Animal | null>(null);
const staticData = ref<Animal[]>(getStaticData(300));
const dynamicSearch = ref(true);
const searchValue = ref('');
const placeholderCountries = ref('Search for a country');
const placeholderAnimals = ref('Search for an animal');
const limit = ref(10);
const debounce = ref(50);
const disabled = ref(false);
const width = ref(300);
const height = ref(40);
const popupHeight = ref(300);
const cornerRadius = ref(4);
const font = ref('20px Arial, sans-serif');
const textColor = ref('#000000');
const primaryColor = ref('#646cff');
const backgroundColor = ref('#ffffff');
const padding = ref(4);
const fetchLatency = ref(300);
const animationSpeed = ref(300);
const staticDataSize = ref(300);
</script>

<template>
	<div v-if="dynamicSearch">
		<h3>Dynamic Country Search</h3>
		<p>
			Selected &nbsp;&nbsp;<b>{{ itemToString(selectedItem) }}</b>
		</p>
		<select-component
			id="country1"
			:placeholder="placeholderCountries"
			:width="width"
			v-model:selected-item="selectedItem"
			:debounce="debounce"
			:disabled="disabled"
			:limit="limit"
			v-model:search="searchValue"
			:search-function="searchFunction"
			:item-to-string="itemToString"
		/>
	</div>

	<div v-if="!dynamicSearch">
		<h3>Static Animal Search</h3>
		<p>
			Selected &nbsp;&nbsp;<b>{{ animalToString(selectedAnimal) }}</b>
		</p>
		<select-component
			id="animal1"
			:placeholder="placeholderAnimals"
			:width="width"
			:items="staticData"
			v-model:selected-item="selectedAnimal"
			:debounce="debounce"
			:disabled="disabled"
			:limit="limit"
			v-model:search="searchValue"
			:item-to-string="animalToString"
		/>
	</div>

	<div class="data-controls">
		<input
			type="radio"
			id="animal"
			name="Date Type"
			style="cursor: pointer"
			:checked="!dynamicSearch"
			@change="() => (dynamicSearch = false)"
		/>

		<label style="cursor: pointer" for="animal">Animal</label>
		<input
			type="radio"
			id="country"
			name="Date Type"
			style="cursor: pointer"
			:checked="dynamicSearch"
			@change="() => (dynamicSearch = true)"
		/>
		<label style="cursor: pointer" for="country">Country</label>

		<div v-if="!dynamicSearch">
			<label title="Number of animals in static list"> Number of animals </label>
			<input
				type="number"
				id="animalCount"
				title="Number of animals in static list"
				:value="staticDataSize"
				step="25"
				@change="
					(event) => {
						staticDataSize = parseInt((event?.target as HTMLInputElement)?.value, 10);
						staticData = getStaticData(staticDataSize);
					}
				"
			/>
		</div>
		<div v-if="dynamicSearch">
			<div>
				<label
					title="Added latency in ms for the dynamic country search (to simulate network latency)"
				>
					Added Latency
				</label>
				<input
					id="fetchLatency"
					type="number"
					title="Added latency in ms for the dynamic country search (to simulate network latency)"
					:value="fetchLatency"
					step="100"
					@change="
						(event) =>
							(fetchLatency = parseInt(
								(event?.target as HTMLInputElement)?.value,
								10
							))
					"
				/>
			</div>
		</div>
	</div>

	<div style="display: flex; flex-direction: row">
		<div class="edit-controls" style="display: flex; flex-direction: column">
			<div>
				<label title="Width of the select component"> Width </label>
				<input
					type="number"
					title="Width of the select component"
					:value="width"
					step="25"
					@change="
						(event) =>
							(width = parseInt((event?.target as HTMLInputElement)?.value, 10))
					"
				/>
			</div>
			<div>
				<label title="Height of the select component"> Height </label>
				<input
					type="number"
					title="Height of the select component"
					:value="height"
					step="5"
					@change="
						(event) =>
							(height = parseInt((event?.target as HTMLInputElement)?.value, 10))
					"
				/>
			</div>
			<div>
				<label title="Max height of the menu popup"> Menu Height </label>
				<input
					type="number"
					:value="popupHeight"
					step="50"
					title="Max height of the menu popup"
					@change="
						(event) =>
							(popupHeight = parseInt((event?.target as HTMLInputElement)?.value, 10))
					"
				/>
			</div>
			<div>
				<label title="Corner radius for the select component"> Corner Radius </label>
				<input
					type="number"
					:value="cornerRadius"
					title="Corner radius for the select component"
					@change="
						(event) =>
							(cornerRadius = parseInt(
								(event?.target as HTMLInputElement)?.value,
								10
							))
					"
				/>
			</div>
			<div id="placeholderContainer">
				<div v-if="dynamicSearch">
					<label title="Placeholder for the select component">
						Placeholder &nbsp;&nbsp;
					</label>
					<input
						type="text"
						id="placeholderInput"
						title="Font for the select component"
						:value="placeholderCountries"
						@input="
							(event) =>
								(placeholderCountries = (event?.target as HTMLInputElement)?.value)
						"
					/>
				</div>
				<div v-if="!dynamicSearch">
					<label title="Placeholder for the select component">
						Placeholder &nbsp;&nbsp;
					</label>
					<input
						type="text"
						id="placeholderInput"
						title="Placeholder for the select component"
						:value="placeholderAnimals"
						@input="
							(event) =>
								(placeholderAnimals = (event?.target as HTMLInputElement)?.value)
						"
					/>
				</div>
			</div>
		</div>
		<div class="edit-controls" style="display: flex; flex-direction: column">
			<div>
				<label title="Text color for the select component"> Text Color </label>
				<input
					type="color"
					:value="textColor"
					title="Text color for the select component"
					@change="(event) => (textColor = (event?.target as HTMLInputElement)?.value)"
				/>
			</div>
			<div>
				<label title="Primary color for the select component"> Prim. Color </label>
				<input
					type="color"
					title="Primary color for the select component"
					:value="primaryColor"
					@change="(event) => (primaryColor = (event?.target as HTMLInputElement)?.value)"
				/>
			</div>
			<div>
				<label title="Background color for the select component"> Background </label>
				<input
					type="color"
					title="Background color for the select component"
					:value="backgroundColor"
					@change="
						(event) => (backgroundColor = (event?.target as HTMLInputElement)?.value)
					"
				/>
			</div>
			<div>
				<label
					title="Padding for murdock UI - used as a hint for the tightness of the layout. Higher values are more spacious"
				>
					Padding
				</label>
				<input
					type="number"
					title="Padding for murdock UI - used as a hint for the tightness of the layout. Higher values are more spacious"
					:value="padding"
					@change="
						(event) =>
							(padding = parseInt((event?.target as HTMLInputElement)?.value, 10))
					"
				/>
			</div>
		</div>
		<div class="edit-controls" style="display: flex; flex-direction: column">
			<div>
				<label title="Whether or not the seclect component is disabled"> Disabled </label>
				<input
					title="Whether or not the select component is disabled"
					type="checkbox"
					:checked="disabled"
					@change="(event) => (disabled = (event.target as HTMLInputElement).checked)"
				/>
			</div>
			<div>
				<label
					title="Debounce. The amount of time in ms to pause after typing before doing a search or filter."
				>
					Debounce
				</label>
				<input
					type="number"
					title="Debounce. The amount of time in ms to pause after typing before doing a search or filter."
					:value="debounce"
					@change="
						(event) =>
							(debounce = parseInt((event?.target as HTMLInputElement)?.value, 10))
					"
				/>
			</div>

			<div>
				<label title="Max number of items to show in the select component"> Limit </label>
				<input
					type="number"
					title="Max number of items to show in the select component"
					:value="limit"
					@change="
						(event) =>
							(limit = parseInt((event?.target as HTMLInputElement)?.value, 10))
					"
				/>
			</div>

			<div>
				<label title="Speed in ms of murdock animations, lower is faster">
					Anim. Speed
				</label>
				<input
					type="number"
					title="Speed in ms of murdock animations, lower is faster"
					:value="animationSpeed"
					step="50"
					@change="
						(event) =>
							(animationSpeed = parseInt(
								(event?.target as HTMLInputElement)?.value,
								10
							))
					"
				/>
			</div>
			<div>
				<label title="Font for the select component"> Font </label>
				<input
					type="text"
					id="fontInput"
					title="Font for the select component"
					:value="font"
					@input="(event) => (font = (event?.target as HTMLInputElement)?.value)"
				/>
			</div>
		</div>
	</div>
</template>

<style>
#root {
	padding: 2rem;
}
:root {
	font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;

	color-scheme: light dark;
	/* color: rgba(255, 255, 255, 0.87); */
	/* background-color: #242424; */

	font-synthesis: none;
	text-rendering: optimizeLegibility;
	-webkit-font-smoothing: antialiased;
	-moz-osx-font-smoothing: grayscale;
}

* {
	font-size: 18px;
}

.data-controls {
	display: flex;
	width: 100%;
	flex-direction: row;
	align-items: center;
	height: 50px;
}
.data-controls label {
	margin-right: 30px;
}
.data-controls #fetchLatency,
#animalCount {
	width: 60px;
}
.edit-controls {
	margin-left: 20px;
}
.edit-controls label {
	margin: 2px;
	padding: 4px;
	display: inline-block;
	width: 120px;
	white-space: nowrap;
}
.edit-controls input {
	width: 60px;
}

#fontInput {
	width: 200px;
}
body {
	margin: 0;
	display: flex;
	min-width: 320px;
	min-height: 100vh;
}

h1 {
	font-size: 3.2em;
	line-height: 1.1;
}

#placeholderContainer {
	position: relative;
	width: 300px;
	margin-right: -100px;
}

#placeholderInput {
	position: absolute;
	top: 5px;
	left: 132px;
	width: 280px;
}
</style>

// angular-examples/src/app/app.component.ts
import { Component, OnInit, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import { SelectComponent } from '@murdock-ui/murdock-angular';
import { faker } from '@faker-js/faker';

export type Country = {
	name: {
		common: string;
	};
};
const wait = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

type Animal = {
	id: number;
	name: string;
};

const search =
	(latency: number) =>
	async (value: string, abortController: AbortController): Promise<Country[]> => {
		const results = await fetch('https://restcountries.com/v3.1/name/' + value, { signal: abortController.signal });
		await wait(latency);
		if (abortController.signal.aborted) {
			throw new Error('Aborted');
		}
		return await results.json();
	};

const fakerFuncs = [
	faker.animal.bear,
	faker.animal.cat,
	faker.animal.dog,
	faker.animal.type,
	faker.animal.fish,
	faker.animal.lion,
	faker.animal.snake,
	faker.animal.cetacean,
	faker.animal.cow,
	faker.animal.horse,
	faker.animal.insect,
	faker.animal.rabbit
];

@Component({
	selector: 'app-root',
	standalone: true,
	imports: [CommonModule, RouterOutlet, SelectComponent],
	templateUrl: './app.component.html',
	styleUrl: './app.component.css'
})
export class AppComponent implements OnInit {
	title = 'murdock-angular';
	@Output() search = '';
	latency = 300;
	searchFunction = search(this.latency);
	@Output() selectedItem: Country | null = null;
	@Output() selectedAnimal: Animal | null = null;
	searchValue: string = '';
	placeholderCountries: string = 'Search for a country';
	placeholderAnimals = 'Search for an animal';

	limit = 10;
	debounce = 50;
	disabled = false;
	width = 300;
	height = 40;
	popupHeight = 300;
	cornerRadius = 4;
	textColor = '#000000';
	primaryColor = '#646cff';
	backgroundColor = '#ffffff';
	padding = 8;
	font = '20px Arial, sans-serif';
	fetchLatency = this.latency;
	staticDataSize = 300;
	dynamicSearch = true;
	animationSpeed = 300;
	@Output() staticData: Animal[] = this.getStaticData(this.staticDataSize);

	constructor() {
		this.setStyles();
	}
	itemToString = (item: Country | null): string => {
		return item?.name.common ?? '';
	};
	animalToString = (animal: Animal | null): string => animal?.name ?? '';
	setDataTypeAnimal() {
		this.dynamicSearch = false;
	}
	setDataTypeCountry() {
		this.dynamicSearch = true;
	}
	getStaticData(length: number): Animal[] {
		// Generate length animal names
		const animals: Set<string> = new Set();
		let loops = 0;
		while (animals.size < length && loops < 1000) {
			const name = fakerFuncs[Math.floor(Math.random() * fakerFuncs.length)]();

			animals.add(name[0].toUpperCase() + name.slice(1));
			loops++;
		}
		return Array.from(animals).map((name, index) => ({ id: index, name }));
	}

	setStaticDataSize(event: Event) {
		const target = event.target as HTMLInputElement;
		const size = parseInt(target.value, 10);
		this.staticDataSize = size;
		this.staticData = this.getStaticData(size);
	}
	setFetchLatency(event: Event) {
		const target = event.target as HTMLInputElement;
		const latency = parseInt(target.value, 10);
		this.fetchLatency = latency;
		this.searchFunction = search(latency);
	}

	setWidth(event: Event) {
		const target = event.target as HTMLInputElement;
		this.width = parseInt(target.value, 10);
		this.setStyles();
	}

	ngOnInit(): void {
		this.setStyles();
	}
	setHeight(event: Event) {
		const target = event.target as HTMLInputElement;
		this.height = parseInt(target.value, 10);
		this.setStyles();
	}

	setPopupHeight(event: Event) {
		const target = event.target as HTMLInputElement;
		this.popupHeight = parseInt(target.value, 10);
		this.setStyles();
	}

	setCornerRadius(event: Event) {
		const target = event.target as HTMLInputElement;
		this.cornerRadius = parseInt(target.value, 10);
		this.setStyles();
	}

	setPlaceholderCountries(event: Event) {
		const target = event.target as HTMLInputElement;
		this.placeholderCountries = target.value;
		this.setStyles();
	}

	setPlaceholderAnimals(event: Event) {
		const target = event.target as HTMLInputElement;
		this.placeholderAnimals = target.value;
		this.setStyles();
	}

	setTextColor(event: Event) {
		const target = event.target as HTMLInputElement;
		this.textColor = target.value;
		this.setStyles();
	}

	setPrimaryColor(event: Event) {
		const target = event.target as HTMLInputElement;
		this.primaryColor = target.value;
		this.setStyles();
	}

	setBackgroundColor(event: Event) {
		const target = event.target as HTMLInputElement;
		this.backgroundColor = target.value;
		this.setStyles();
	}

	setPadding(event: Event) {
		const target = event.target as HTMLInputElement;
		this.padding = parseInt(target.value, 10);
		this.setStyles();
	}

	setDisabled(event: Event) {
		const target = event.target as HTMLInputElement;
		this.disabled = target.checked;
		this.setStyles();
	}

	setDebounce(event: Event) {
		const target = event.target as HTMLInputElement;
		this.debounce = parseInt(target.value, 10);
		this.setStyles();
	}

	setLimit(event: Event) {
		const target = event.target as HTMLInputElement;
		this.limit = parseInt(target.value, 10);
		this.setStyles();
	}

	setAnimationSpeed(event: Event) {
		const target = event.target as HTMLInputElement;
		this.animationSpeed = parseInt(target.value, 10);
		this.setStyles();
	}

	setFont(event: Event) {
		const target = event.target as HTMLInputElement;
		this.font = target.value;
		this.setStyles();
	}

	setStyles() {
		document.getElementById('root')?.style.setProperty('--mk-select-max-menu-height', this.popupHeight + 'px');
		document.getElementById('root')?.style.setProperty('--mk-corner-radius', this.cornerRadius + 'px');
		document.getElementById('root')?.style.setProperty('--mk-text-color', this.textColor);
		document.getElementById('root')?.style.setProperty('--mk-primary-color', this.primaryColor);
		document.getElementById('root')?.style.setProperty('--mk-background-color', this.backgroundColor);
		document.getElementById('root')?.style.setProperty('--mk-padding', this.padding + 'px');
		document.getElementById('root')?.style.setProperty('--mk-select-height', this.height + 'px');
		document.getElementById('root')?.style.setProperty('--mk-select-width', this.width + 'px');
		document.getElementById('root')?.style.setProperty('--mk-select-font', this.font);
		document.getElementById('root')?.style.setProperty('--mk-animation-speed', this.animationSpeed + 'ms');
	}
}

<div id="root">


    @if (dynamicSearch) {
    <div>
        <h3>Dynamic Country Search</h3>
        <p>Selected &nbsp;&nbsp;<b>{{itemToString(selectedItem)}}</b></p>
        <select-component id="country1" [placeholder]="placeholderCountries" [width]="width"
            [(selectedItem)]="selectedItem" [debounce]="debounce" [disabled]="disabled" [limit]="limit"
            [(search)]="searchValue" [searchFunction]="searchFunction" [itemToString]="itemToString" />
    </div>
    } @else {

    <div>
        <h3>Static Animal Search</h3>
        <p>Selected &nbsp;&nbsp;<b>{{animalToString(selectedAnimal)}}</b></p>
        <select-component id="animal1" [placeholder]="placeholderAnimals" [width]="width" [items]="staticData"
            [(selectedItem)]="selectedAnimal" [debounce]="debounce" [disabled]="disabled" [limit]="limit"
            [(search)]="searchValue" [itemToString]="animalToString" />
    </div>
    }
    <div class='data-controls'>

        <input type='radio' id='animal' name="Date Type" style='cursor: pointer;' [checked]="!dynamicSearch"
            (change)="setDataTypeAnimal()" />
        <label style='cursor: pointer;' for='animal'>Animal</label>
        <input type='radio' id='country' name="Date Type" style='cursor: pointer;' [checked]="dynamicSearch"
            (change)="setDataTypeCountry()" />
        <label style='cursor: pointer;' for="country">Country</label>

        @if (!dynamicSearch) {
        <div>
            <label title='Number of animals in static list'>
                Number of animals
            </label>
            <input type="number" id="animalCount" title='Number of animals in static list' [value]="staticDataSize"
                step="25" (change)="setStaticDataSize($event)" />
        </div>
        } @else {
        <div>

            <div>
                <label title='Added latency in ms for the dynamic country search (to simulate network latency)'>
                    Added Latency
                </label>
                <input id='fetchLatency' type="number"
                    title='Added latency in ms for the dynamic country search (to simulate network latency)'
                    [value]="fetchLatency" step="100" (change)="setFetchLatency($event)" />
            </div>
        </div>

        }


    </div>

    <div style='display: flex; flex-direction: row'>


        <div class='edit-controls' style='display: flex; flex-direction: column'>
            <div>
                <label title='Width of the select component'>
                    Width
                </label>
                <input type="number" title='Width of the select component' [value]="width" step="25"
                    (change)="setWidth($event)" />
            </div>
            <div>
                <label title='Height of the select component'>
                    Height
                </label>
                <input type="number" title='Height of the select component' [value]="height" step="5"
                    (change)="setHeight($event)" />
            </div>
            <div>
                <label title='Max height of the menu popup'>
                    Menu Height
                </label>
                <input type="number" [value]="popupHeight" step="50" title='Max height of the menu popup'
                    (change)="setPopupHeight($event)" />
            </div>
            <div>
                <label title='Corner radius for the select component'>
                    Corner Radius
                </label>
                <input type="number" [value]="cornerRadius" title='Corner radius for the select component'
                    (input)="setCornerRadius($event)" />
            </div>
            <div id="placeholderContainer">
                @if (dynamicSearch) {
                <div>
                    <label title='Placeholder for the select component'>
                        Placeholder &nbsp;&nbsp;
                    </label>
                    <input type="text" id='placeholderInput' title='Font for the select component'
                        [value]="placeholderCountries" (input)="setPlaceholderCountries($event)" />
                </div>
                } @else {
                <div>
                    <label title='Placeholder for the select component'>
                        Placeholder &nbsp;&nbsp;
                    </label>
                    <input type="text" id='placeholderInput' title='Placeholder for the select component'
                        [value]="placeholderAnimals" (input)="setPlaceholderAnimals($event)" />
                </div>}
            </div>


        </div>
        <div class='edit-controls' style='display: flex; flex-direction: column'>
            <div>
                <label title='Text color for the select component'>
                    Text Color
                </label>
                <input type="color" [value]="textColor" title='Text color for the select component'
                    (change)="setTextColor($event)" />
            </div>
            <div>
                <label title='Primary color for the select component'>
                    Prim. Color
                </label>
                <input type="color" title='Primary color for the select component' [value]="primaryColor"
                    (change)="setPrimaryColor($event)" />

            </div>
            <div>
                <label title='Background color for the select component'>
                    Background
                </label>
                <input type="color" title='Background color for the select component' [value]="backgroundColor"
                    (change)="setBackgroundColor($event)" />
            </div>
            <div>
                <label
                    title='Padding for murdock UI - used as a hint for the tightness of the layout. Higher values are more spacious'>
                    Padding
                </label>
                <input type="number"
                    title='Padding for murdock UI - used as a hint for the tightness of the layout. Higher values are more spacious'
                    [value]="padding" (change)="setPadding($event)" />
            </div>




        </div>
        <div class='edit-controls' style='display: flex; flex-direction: column'>
            <div>
                <label title='Whether or not the seclect component is disabled'>
                    Disabled
                </label>
                <input title='Whether or not the seclect component is disabled' type="checkbox" [checked]="disabled"
                    (change)="setDisabled($event)" />
            </div>
            <div>
                <label
                    title='Debounce. The amount of time in ms to pause after typing before doing a search or filter.'>
                    Debounce
                </label>
                <input type="number"
                    title='Debounce. The amount of time in ms to pause after typing before doing a search or filter.'
                    [value]="debounce" (change)="setDebounce($event)" />
            </div>

            <div>
                <label title='Max number of items to show in the select component'>
                    Limit
                </label>
                <input type="number" title='Max number of items to show in the select component' [value]="limit"
                    (change)="setLimit($event)" />

            </div>

            <div>
                <label title='Speed in ms of murdock animations, lower is faster'>
                    Anim. Speed
                </label>
                <input type="number" title='Speed in ms of murdock animations, lower is faster' [value]="animationSpeed"
                    step="50" (change)="setAnimationSpeed($event)" />
            </div>
            <div>
                <label title='Font for the select component'>
                    Font
                </label>
                <input type="text" id='fontInput' title='Font for the select component' [value]="font"
                    (input)="setFont($event)" />
            </div>


        </div>
    </div>

</div>

<router-outlet></router-outlet>
