// murdock-angular/src/app/app.component.ts
import { Component, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import { SelectComponent } from './select.component.js';
import { Country } from '../index.js';

@Component({
	selector: 'app-root',
	standalone: true,
	imports: [CommonModule, RouterOutlet, SelectComponent],
	templateUrl: './app.component.html',
	styleUrl: './app.component.css'
})
export class AppComponent {
	title = 'murdock-angular';
	// @Output() search = '';
	// @Output() selectedItem: Country | null = null;
	@Output() searchFunc = async (value: string, abortController: AbortController): Promise<Country[]> => {
		const results = await fetch('https://restcountries.com/v3.1/name/' + value, {
			signal: abortController.signal
		});

		if (abortController.signal.aborted) {
			throw new Error('Aborted');
		}
		// eslint-disable-next-line @typescript-eslint/no-explicit-any
		return await results.json();
	};
	@Output() itemToString = (item: Country): string => {
		return item?.name?.common;
	};
}

<div class="content">
    <select-component [searchFunction]="searchFunc" [itemToString]="itemToString">
    </select-component>
</div>
<!-- <div>{{selectedItem&&itemToString(selectedItem)}}</div> -->
<input />


<router-outlet></router-outlet>

// react-examples/src/App.tsx
import { useState } from 'react'
import React from 'react';
import './App.css';
import './theme.css';
import { SelectComponent } from '@murdock-ui/murdock-react/select-component';

export type Country = {
    name: {
        common: string;
    };
}
const search = async (value: string, abortController: AbortController): Promise<Country[]> => {
    const results = await fetch("https://restcountries.com/v3.1/name/" + value, { signal: abortController.signal });

    if (abortController.signal.aborted) {
        throw new Error("Aborted");
    }
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    return await results.json();
}
function App() {
    // const [count, setCount] = useState(0)
    const [selectedItem, setSelectedItem] = useState<Country | null>(null);


    const [searchValue, setSearchValue] = useState("");
    console.log(searchValue);
    return (
        <>
            <h1>{selectedItem?.name.common}</h1>
            <SelectComponent id="country" width={300} overrideClassName="mk-select-root myclass" selectedItem={selectedItem} setSelectedItem={setSelectedItem} debounce={50} limit={10} search={searchValue} setSearch={setSearchValue} searchFunction={search} itemToString={(item) => item.name.common} />


        </>
    )
}

export default App
